### ISSUE TITLE
Readme: JAM TESTNET Roadmap Year

### ISSUE THREAD

**Issue by Blockcowboy2** [jam-duna/jamtestnet#2]
**Q1 2024:** We hope a similar number of teams can run through guaranteeing, assuring and auditing with preimages with a small battery of work packages. We imagine M1 test vectors would be available at this time for teams to test against as well.
**Q2 2024:** We hope a similar number of teams can finalize with GRANDPA and BEEFY, use BLS and reach conformed

Should this be :
Q1 2025
Q2 2025

?

**Comment by sourabhniyogi** [comment]
Fixed!
